name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Cache
        uses: actions/cache@v2
        with:
          path: "./src/js/node_modules"
          key: node-modules-${{ hashFiles('./src/js/package.json') }}
      - name: Run tests
        working-directory: ./src/js
        run: |
          npm ci
          npm run test
